### ISSUE TITLE
Request for pre-trained model

### ISSUE THREAD

**Issue by GrayXu** [HyeOn-62/Pytorch_JPPNet#1]
Hi, I'm interested about this pytorch implementation. 
But it seems like I cannot download weights (pre-trained models) from dropbox.
I would appreciate it if you can upload a new one.
Thx!

**Comment by ocean-joo** [comment]
Hi, GrayXu!
Thanks for visiting our repository.
With your request, we're sorry to tell you that we don't have pre-trained weight for Pytorch model. 
We have original pre-trained weight from TensorFlow model converted to Pytorch's weight structure, but it seems not working on Pytorch model for some reason. 
Though if you want the converted weight, please contact us again.
